### ISSUE TITLE
TODO checklist for 2022

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/AirMonitorIngest#1]
Items as they come up:

-----
_TODO:_

- [ ] Use password in `wrcc_downloadData()`
- [ ] `airnow_updateUnknownLocations()` should handle empty data coming in
- [ ] `epa_aqs_updateKnownLocations()` -- perform work currently in .Rmd files

----
_Items finished on 2022-06-16_

- [x] Change `wrcc_identifyMonitorType()` to `wrcc_identifyDataFormat()` and update wrcc data ingest script
- [x] wrcc latest data `meta` has _named_ longitude and latitude values which messes up conversion to/from JSON (5/05)

----
_Items finished on 2022-01-25_

- [x] Change `wrcc_getDailyUnitIDs()` to `wrcc_gettUnitIDs()`

----
_Items finished on 2021-11-04_

- [x] `airnow_updateKnownLocations()` -- download sites info and create/update known locations table 
----
_Items finished on 2021-10-27_

- [x] EPA ingest should create an `AQSID` parameter which we will describe as _core metadata_ for air quality data
-----
_Items finished on 2021-10-24_

- [x] update to get `parameterRawConcentration` and `AQI`
