### ISSUE TITLE
TODO checklist for 2023

### ISSUE THREAD

**Issue by jonathancallahan** [pnwairfire/AirMonitorIngest#2]
Items as they come up:

-----
_TODO:_

- [ ] asdf

Leftovers from 2022
- [ ] Use password in `wrcc_downloadData()` (2022)
- [ ] `airnow_updateUnknownLocations()` should handle empty data coming in (2022)
- [ ] `epa_aqs_updateKnownLocations()` -- perform work currently in .Rmd files (2022)

----
_Items finished on 2023-06-30_
